version: 1.0.{build}
platform:
  - x86
  - x64

build:
  verbosity: quiet

install:
  - cup all -v
  - cinst -y jdk8 nodejs.install
  - refreshenv
  - java -version

test_script:
  - mvn clean install

branches:
  only:
    - master