version: 1.0.{build}
platform:
  - x86
  - x64

build:
  verbosity: quiet

install:
  - java -version
  - dir
  - echo %cd%
  - mvn clean install

build_script:
  - mvn clean install

test_script:
  - mvn clean install

branches:
  only:
    - master