version: 1.0.{build}
platform:
  - x86
  - x64

build:
  verbosity: quiet

install:
  - cup all -v
  - cinst -y maven
  - refreshenv
  - java -version
  - mvn -version
  - dir
  - echo %cd%

test_script:
  - mvn clean install

branches:
  only:
    - master